### ISSUE TITLE
File Loading Issue (Chrome/desktop app only)

### ISSUE THREAD

**Issue by PokeSamuri** [juliandescottes/piskel#368]
I downloaded your app on Mac. I was working on a file and saved it earlier. Now the file won't load up and I keep getting this message.

Uncaught node.js Error 
RangeError: Invalid string length
    at Object.stringify (native)
    at Object.a.Serializer.serializePiskel (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:8:27174)
    at a.PiskelController.serialize (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:15:12302)
    at a.HistoryService.saveState (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:20:30203)
    at a.HistoryService.onSaveStateEvent (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:20:29734)
    at Object.$.event.dispatch (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:2:5590)
    at Object.g.handle.h (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:2:1604)
    at Object.$.event.trigger (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:2:4135)
    at Object.<anonymous> (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:2:11972)
    at Function.$.extend.each (file:///Users/s141676/Desktop/untitled%20folder/Piskel.app/Contents/Resources/app.nw/dest/js/piskel-packaged-min-2015-10-25-12-33.js:1:14321)

**Comment by juliandescottes** [comment]
Can you attach or send me the file you're trying to load ?

**Comment by PokeSamuri** [comment]
It won't allow me to attach the .piskel file to this

**Comment by juliandescottes** [comment]
Can you send it to me by email ? julian.descottes@gmail.com

**Comment by PokeSamuri** [comment]
I emailed it to you

**Comment by juliandescottes** [comment]
Just received it, thanks!

It loads fine on Firefox, but fails on Chrome, with the error message you mentioned.
Since the desktop version is based on Chrome, it's probably the same issue.

I will have a look.

**Comment by juliandescottes** [comment]
Adding the piskel file as txt here for reference.

[Buster_Vs_Megaman.txt](https://github.com/juliandescottes/piskel/files/61831/Buster_Vs_Megaman.txt)
